#!/usr/bin/env bash
# Configures an Nginx server to listen on prt 80

# removes the default Nginx configuration file

rm /etc/ngnix/sites-enabled/default

# Configure Nginx to listen on port 80 for all active IPV4 IPs

# restart nginx
service nginx restart
