#!/usr/bin/env bash
#Bash script that displays Best School 10 times.
#for the 9th iteration, displays Best School then Hi on a new line.

j=0

while [ $j -lt 10 ]
do
  echo "Best School"
  if [ $j -eq 8 ]
  then
    echo "Hi"
  fi
  (( j++ ))
done
