#!/usr/bin/env bash
#displays the time for 12 hours and 59 minutes:

#display hours from 0 to 12
#display minutes from 1 to 59

j=0

while [ $j -lt 13 ]
do
  echo "Hour: $j"
  j=1
  while [ $j -lt 60 ]
  do
    echo $j
    (( j++ ))
  done
  (( j++ ))
done
